import SideBar from "@/components/SideBar";
import "./globals.css";
import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import TopBar from "@/components/TopBar";

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${publicSans.className} grid grid-cols-[1fr_5fr]`}>
        <SideBar />
        <div className="w-full ">
          <TopBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
